#!/usr/bin/env bash

set -euo  pipefail

PROJECT_DIR="$(pwd)"/llvm-project

git clone --depth 1 https://github.com/llvm/llvm-project.git "${PROJECT_DIR}" || pushd "${PROJECT_DIR}" && git pull --ff-only && popd

mkdir -p ./build/
cd build

cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt" -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" -DCMAKE_INSTALL_PREFIX="$HOME"/llvm ${PROJECT_DIR}/llvm

ninja install

sudo update-alternatives --install /usr/bin/clang++ clang++ "${HOME}"/clang/bin/clang++ 0
sudo update-alternatives --install /usr/bin/clang clang "${HOME}"/clang/bin/clang 0
