#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR="$(pwd)"/gcc

sudo apt-get install flex libgmp-dev libmpfr-dev libmpc-dev

git clone git://gcc.gnu.org/git/gcc.git "${PROJECT_DIR}" || pushd "${PROJECT_DIR}" && git pull --ff-only && popd

mkdir -p ./build/
cd build

"${PROJECT_DIR}"/configure --disable-bootstrap --disable-multilib --prefix="${HOME}"/gcc/ --enable-languages=c,c++,lto
make -j "$(nproc)"
make install

sudo update-alternatives --install /usr/bin/g++ g++ "${HOME}"/gcc/bin/g++ 0
sudo update-alternatives --install /usr/bin/gcc gcc "${HOME}"/gcc/bin/gcc 0
