#!/usr/bin/env bash
set -o errexit

#export TSOCKS_DEBUG=255
export TSOCKS_DEBUG=1
export LD_PRELOAD=/usr/lib/libtsocks.so.1.8

echo --------------------------------------------------------------------------------
echo $*
echo --------------------------------------------------------------------------------

$*

exit $?
